Norman init
PeteMango/CS247-Chess pull request #7
Opened 2024-07-24 02:29 UTC by normanchenn

2024-07-24 02:30 UTC, Chen-Prototypes submitted a review, later dismissed

2024-07-25 15:11 UTC, PeteMango requested changes

2024-07-25 15:11 UTC, PeteMango commented on include/board.h
> +    Board(int i);
the board constructor with (int i) should be merged into the default constructor

2024-07-25 15:11 UTC, PeteMango commented on include/chess.h
> +    void setup_board(std::istream& in, bool& is_eof_given);
well done! smart workaround!

2024-07-25 15:11 UTC, PeteMango commented on src/display/textdisplay.cpp
> +    for (int row = 7; row >= 0; row--) {
wrong, fix this

2024-07-25 20:18 UTC, PeteMango approved these changes
lgtm

2024-07-25 20:18 UTC, merged